# FICTIONAL SAMPLE — /etc/open5gs/ausf.yaml

logger:
  file:
    path: /var/log/open5gs/ausf.log
  level: info

global:
  max:
    ue: 4096

ausf:
  sbi:
    server:
      - address: 127.0.0.11
        port: 7777
        advertise: open5gs-ausf.example.net:7777
    client:
      scp:
        - uri: http://127.0.0.200:7777
  metrics:
    server:
      - address: 127.0.0.11
        port: 9090
