# FICTIONAL SAMPLE — /etc/open5gs/udr.yaml

db_uri: mongodb://127.0.0.1/open5gs

logger:
  file:
    path: /var/log/open5gs/udr.log
  level: info

global:
  max:
    ue: 4096

udr:
  sbi:
    server:
      - address: 127.0.0.20
        port: 7777
        advertise: open5gs-udr.example.net:7777
    client:
      scp:
        - uri: http://127.0.0.200:7777
  metrics:
    server:
      - address: 127.0.0.20
        port: 9090
