#!/usr/bin/env python3
"""
Build mme.access_control YAML from a site CSV (TAC + eNodeB allow-list).

Example:
  python scripts/gen_roam_access_from_csv.py \\
    --csv "../LTE/roam-sites.example.csv" \\
    --prefix 00101 --prefix 99970 \\
    --output configs/open5gs/roam-access.generated.yaml

Merge the output into /etc/open5gs/mme.yaml (full `mme:` fragment). Each --prefix
becomes one whitelist entry; site lists are shared across all prefixes.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path


def load_sites(csv_path: Path, roaming_column: str) -> tuple[list[int], list[int]]:
    tacs: set[int] = set()
    enbs: set[int] = set()

    with csv_path.open(newline="", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            flag = (row.get(roaming_column) or "").strip().upper()
            if flag and flag not in ("YES", "Y", "1", "TRUE"):
                continue
            tac_s = (row.get("TAC (DEC)") or "").strip().replace(",", "")
            enb_s = (row.get("ENODEB_ID(DEC)") or "").strip().replace(",", "")
            if tac_s:
                tacs.add(int(tac_s))
            if enb_s:
                enbs.add(int(enb_s))

    return sorted(tacs), sorted(enbs)


def yaml_int_list(values: list[int], indent: int) -> list[str]:
    pad = " " * indent
    return [f"{pad}- {v}" for v in values]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--csv", required=True, type=Path)
    ap.add_argument("--prefix", action="append", required=True,
                    help="IMSI BCD prefix (e.g. 00101 for example roam PLMN)")
    ap.add_argument("--output", type=Path, help="Write YAML fragment here")
    ap.add_argument("--plmn", action="append", metavar="MCC-MNC",
                    help="Home PLMN allow-list entry, e.g. 999-70 (repeatable)")
    ap.add_argument("--reject-cause", type=int, default=13,
                    help="NAS EMM cause when location not allowed (default: 13)")
    ap.add_argument("--final", action="store_true",
                    help="Emit full mme: fragment (time + plmn + roam entries)")
    ap.add_argument("--roaming-column", default="Roaminng",
                    help="CSV column name for YES/NO (default: Roaminng)")
    args = ap.parse_args()

    if not args.csv.is_file():
        print(f"CSV not found: {args.csv}", file=sys.stderr)
        return 1

    tacs, enbs = load_sites(args.csv, args.roaming_column)
    if not tacs and not enbs:
        print("No TAC/eNB rows loaded from CSV", file=sys.stderr)
        return 1

    out: list[str] = [
        "# Generated by scripts/gen_roam_access_from_csv.py",
        "# Gitignored — merge into /etc/open5gs/mme.yaml (or replace mme.access_control)",
        "mme:",
        "  access_control:",
        f"    - default_reject_cause: {args.reject_cause}",
    ]

    for prefix in args.prefix:
        out.append(f'    - imsi_prefix: "{prefix}"')
        out.append(f"      reject_cause: {args.reject_cause}")
        out.append("      tac:")
        out.extend(yaml_int_list(tacs, indent=8))
        out.append("      enb_id:")
        out.extend(yaml_int_list(enbs, indent=8))

    text = "\n".join(out) + "\n"

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
        print(f"Wrote {args.output} ({len(tacs)} TACs, {len(enbs)} eNB-IDs, "
              f"{len(args.prefix)} prefix(es))")
    else:
        sys.stdout.write(text)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
